<!--<h1><?php echo $this->translate('Heroadd') ?></h1>
<?php echo $this->partial('forms/heroadd-form.phtml', array('form' => $HeroaddForm)); ?>
-->

<div class='header'>
    <ul class="service-bar">
        <li class="service-cell">
            <a href="http://www.battlenet.com.cn/"  title="首页" data-action="Battle.net Home"> </a>
        </li>
        <li class="service-cell">
            <a href="/user/login/" onclick="return Login.open()">登录</a>
            或者
            <a href="/user/register/">注册账号</a>
        </li>
        <li class="service-cell">
            <a class="service-link" href="https://www.battlenet.com.cn/shop/" data-action="Shop">充值</a>
        </li>
        <li class="service-cell">
            <a class="service-link" href="https://www.battlenet.com.cn/account/management/" data-action="Account">客服</a>
        </li>

    </ul>

</div>