<?php echo $this->doctype(); ?>
<?php $form = $this->form; ?>
<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form) ?>
    <div class="control-group <?php echo count($form->get('heroname')->getMessages()) > 0 ? 'error' : '' ?>">
        <?php echo $this->formLabel($form->get('heroname')); ?>
        <div class="controls">
            <?php echo $this->formElement($form->get('heroname')); ?>
            <?php echo $this->formElementErrors($form->get('heroname')) ?>
        </div>
    </div>
<?php /*
<div class="control-group <?php echo count($form->get('vocationid')->getMessages()) > 0 ? 'error' : '' ?>">
    <?php echo $this->formLabel($form->get('vocationid')); ?>
    <div class="controls">
        <?php echo $this->formElement($form->get('vocationid')); ?>
        <?php echo $this->formElementErrors($form->get('vocationid')) ?>
    </div>
</div>
*/?>
    <div class="btn-group" data-toggle="buttons-radio">
        <?php for($i=0,$count=11;$i<$count/3;$i++){?>

        <div>
            <?php if(($i*3+0)<$count) {?>
                <button type="button" class="btn btn-primary"><?php print_r('vocationname');echo $i*3+0; ?></button>
            <?php }?>
            <?php if(($i*3+1)<$count) {?>
                <button type="button" class="btn btn-primary"><?php print_r('vocationname');echo $i*3+1; ?></button>
            <?php }?>
            <?php if(($i*3+2)<$count) {?>
                <button type="button" class="btn btn-primary"><?php print_r('vocationname');echo $i*3+2; ?></button>
            <?php }?>
        </div>

        <?php }?>
    </div>

    <div class="control-group <?php echo count($form->get('raceid')->getMessages()) > 0 ? 'error' : '' ?>">
        <?php echo $this->formLabel($form->get('raceid')); ?>
        <div class="controls">
            <?php echo $this->formElement($form->get('raceid')); ?>
            <?php echo $this->formElementErrors($form->get('raceid')); ?>
        </div>
    </div>
<div class="control-group <?php echo count($form->get('gender')->getMessages()) > 0 ? 'error' : '' ?>">
    <label class="control-label">Gender</label>
    <div class="controls">
        <?php echo $this->formElement($form->get('gender')); ?>
        <?php echo $this->formElementErrors($form->get('gender')); ?>
    </div>
</div>

    <div class="control-group">
        <div class="controls">
            <?php echo $this->formElement($form->get('addhero')); ?>
        </div>
    </div>


<?php echo $this->form()->closeTag() ?>