<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('My social network'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/"><?php echo $this->translate('My social network') ?></a>
            <div class="nav-collapse collapse"></div>
        </div>
    </div>
</div>
<div class="container wrapper">
<!--    <?php echo $this->flashMessengerHelper() ?>
    <?php echo $this->content; ?>
-->
    <div class="First"><h1>后台管理</h1></div>
    <div class="Second"><h3><a href="/keep/hero/add">Hero</a></h3></div>
    <div class="Second"><h3><a href="/keep/camp/add">Camp</a></h3></div>
    <div class="Second"><h3><a href="/keep/race/add">Race</a></h3></div>
    <div class="Second"><h3><a href="/keep/step/add">Step</a></h3></div>
    <div class="Second"><h3><a href="/keep/skill/add">Skill</a></h3></div>
    <div class="Second"><h3><a href="/keep/vocation/add">Vocation</a></h3></div>



</div>
<footer>
    <div class="container fluid-row">
        <?php echo $this->translate('Welcome to my Social Network | Learn how to create a Social Network with ZF2 &copy; 2013') ?>
    </div>
</footer>

<?php echo $this->inlineScript() ?>
</body>
</html>
